{% set name = "tomli" %}
{% set version = "1.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tomli-{{ version }}.tar.gz
  sha256: c6ce0015eb38820eaf32b5db832dbc26deb3dd427bd5f6556cf0acac2c214fee

build:
  number: 0
  noarch: python
  script:
    # Removing pyproject.toml here due to pip bug
    - {{ PYTHON }} -c "__import__('os').unlink('pyproject.toml')"
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit-core
    - pip
    - poetry
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - tomli
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hukkin/tomli
  summary: A simple TOML parser
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
