{% set name = "tomli" %}
{% set version = "1.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: tomli
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tomli-{{ version }}.tar.gz
    sha256: c6ce0015eb38820eaf32b5db832dbc26deb3dd427bd5f6556cf0acac2c214fee
  - folder: flit-core
    url: https://github.com/takluyver/flit/archive/refs/tags/3.4.0.tar.gz
    sha256: 7d5482cfa6ff2a58282d8f102566d03caa91807b70534ed3abdd5ac6123dbfdb
    

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} ./flit-core/flit_core/build_dists.py
    - ls ./flit-core
    - {{ PYTHON }} -m pip install ./flit-core/flit_core/dist/flit_core-3.4.0-py3-none-any.whl -vv
    # Removing pyproject.toml here due to pip bug
    - {{ PYTHON }} -c "__import__('os').unlink('./tomli/pyproject.toml')"
    - {{ PYTHON }} -m pip install ./tomli/. -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - tomli
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hukkin/tomli
  summary: A simple TOML parser
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
