{% set name = "tomli" %}
{% set version = "1.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tomli-{{ version }}.tar.gz
    sha256: c6ce0015eb38820eaf32b5db832dbc26deb3dd427bd5f6556cf0acac2c214fee

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    # Cannot use flit-core >3.3.0 due to cyclic dependency 
    - flit-core 3.3.0
    - pip
    - python
  run:
    - python >=3.6

test:
  imports:
    - tomli
  commands:
    - pip check
  requires:
    - pip
    - python <3.10

about:
  home: https://github.com/hukkin/tomli
  summary: A simple TOML parser
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/hukkin/tomli
  doc_url: https://github.com/hukkin/tomli/blob/master/README.md

extra:
  recipe-maintainers:
    - thewchan
