{% set name = "tomli" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tomli-{{ version }}.tar.gz
  sha256: 33d7984738f8bb699c9b0a816eb646a8178a69eaa792d258486776a5d21b8ca5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit-core
    - pip
    - poetry
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - tomli
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hukkin/tomli
  summary: A simple TOML parser
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
